---
min_acl: public
github_url: https://github.com/barteljan/VISPER.git
readme: ../docs/README-VISPER-Presenter.md
author: Jan Bartel
clean:
sdk: iphonesimulator
output: ../docs/VISPER-Presenter/Swift
module: VISPER-Presenter
framework_root: Classes/Swift
podspec: "VISPER-Presenter.podspec" 
