use_frameworks!

platform :ios, '8.0'

target 'VISPER_Example' do
  pod 'VISPER', :path => '../'
  pod 'VISPER-CommandBus'
end

target 'VISPER-Wireframe-Example' do
    pod 'VISPER-Wireframe', :path => '../'
    pod 'VISPER-Wireframe-Core', :path => '../'
    pod 'VISPER-Wireframe-UIViewController', :path => '../'
    pod 'VISPER-Wireframe-Objc', :path => '../'
end

target 'VISPER-Wireframe-Tests' do
    pod 'VISPER-Wireframe', :path => '../'
    pod 'VISPER-Wireframe-Core', :path => '../'
    pod 'VISPER-Wireframe-UIViewController', :path => '../'
    pod 'VISPER-Wireframe-Objc', :path => '../'
end

target 'VISPER-Swift-Example' do
    pod 'VISPER-Swift/RxSwift', :path => '../'
    pod 'VISPER-Wireframe', :path => '../'
    pod 'VISPER-Wireframe-Core', :path => '../'
    pod 'VISPER-Wireframe-UIViewController', :path => '../'
    pod 'VISPER-Wireframe-Objc', :path => '../'
    pod 'VISPER-Redux', :path => '../'
    pod 'VISPER-Reactive', :path => '../'
end

target 'VISPER-Redux-Example' do
    pod 'VISPER-Redux', :path => '../'
    pod 'VISPER-Reactive', :path => '../'
end

target 'VISPER-Redux-Tests' do
    pod 'VISPER-Redux', :path => '../'
    pod 'VISPER-Reactive', :path => '../'
end

target 'VISPER-Reactive-Example' do
    pod 'VISPER-Reactive', :path => '../'
end

target 'VISPER-Reactive-Tests' do
    pod 'VISPER-Reactive', :path => '../'
end

target 'VISPER-Reactive-RxSwift-Tests' do
    pod 'RxSwift'
    pod 'VISPER-Reactive/RxSwift', :path => '../'
end

