use_frameworks!
platform :ios, '13.0'

target 'VISPER_Example' do
  pod 'VISPER', :path => '../'
  pod 'VISPER-CommandBus'
end

target 'VISPER-Wireframe-Example' do
    pod 'VISPER-Wireframe', :path => '../'
    pod 'VISPER-Core', :path => '../'
    pod 'VISPER-UIViewController', :path => '../'
    pod 'VISPER-Objc', :path => '../'
end

target 'VISPER-Wireframe-Tests' do
    pod 'VISPER-Wireframe', :path => '../'
    pod 'VISPER-Core', :path => '../'
    pod 'VISPER-UIViewController', :path => '../'
    pod 'VISPER-Objc', :path => '../'
    pod 'VISPER-Presenter', :path => '../'
end

target 'VISPER-Swift-Example' do
    pod 'VISPER', :path => '../'
    pod 'VISPER-Swift', :path => '../'
    pod 'VISPER-Wireframe', :path => '../'
    pod 'VISPER-Core', :path => '../'
    pod 'VISPER-UIViewController', :path => '../'
    pod 'VISPER-Objc', :path => '../'
    pod 'VISPER-Redux', :path => '../'
    pod 'VISPER-Reactive', :path => '../'
    pod 'VISPER-Presenter', :path => '../'
end

target 'VISPER-Swift-RxSwift-Example' do
    pod 'VISPER', :path => '../'
    pod 'VISPER-Swift', :path => '../'
    pod 'VISPER-Wireframe', :path => '../'
    pod 'VISPER-Core', :path => '../'
    pod 'VISPER-UIViewController', :path => '../'
    pod 'VISPER-Objc', :path => '../'
    pod 'VISPER-Redux', :path => '../'
    pod 'VISPER-Reactive/RxSwift', :path => '../'
    pod 'VISPER-Presenter', :path => '../'
end

target 'VISPER-Redux-Example' do
    pod 'VISPER-Redux', :path => '../'
    pod 'VISPER-Reactive', :path => '../'
end

target 'VISPER-Redux-Tests' do
    pod 'VISPER-Redux', :path => '../'
    pod 'VISPER-Reactive', :path => '../'
end

target 'VISPER-Sourcery-Example' do
    pod 'VISPER', :path => '../'
    pod 'VISPER-Redux', :path => '../'
    pod 'VISPER-Sourcery', :path => '../'
end

target 'VISPER-Entity-Example' do
    pod 'VISPER-Entity', :path => '../'
end

target 'VISPER-Entity-ExampleTests' do
    pod 'VISPER-Entity', :path => '../'
end

target 'VISPER-Reactive-Tests' do
    pod 'VISPER-Reactive', :path => '../'
end

target 'VISPER-Reactive-RxSwift-Tests' do
    pod 'RxSwift'
    pod 'VISPER-Reactive/RxSwift', :path => '../'
end

target 'VISPER-UIViewController-Tests' do
    pod 'VISPER-UIViewController', :path => '../'
    pod 'VISPER-Presenter', :path => '../'
    pod 'VISPER-Wireframe', :path => '../'
end

