source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'VISPER_Example', :exclusive => true do
  pod "VISPER", :path => "../"
end

target 'VISPER_Tests', :exclusive => true do
  pod "VISPER", :path => "../"

#pod 'Kiwi'
end
