---
min_acl: public
github_url: https://github.com/barteljan/VISPER.git
readme: README.md
author: Jan Bartel
clean:
sdk: iphonesimulator
objc: true
output: docs/
module: VISPER
umbrella_header: Pod/Classes/VISPER.h 
framework_root: Pod/Classes
