---
min_acl: public
github_url: https://github.com/barteljan/VISPER.git
readme: ../docs/README-VISPER-Core.md
author: Jan Bartel
clean:
sdk: iphonesimulator
output: ../docs/VISPER-Core
module: VISPER-Core
framework_root: Classes
podspec: "VISPER-Core.podspec" 
