---
min_acl: public
github_url: https://github.com/barteljan/VISPER.git
readme: ../docs/README-VISPER-Objc.md
author: Jan Bartel
clean:
sdk: iphonesimulator
output: ../docs/VISPER-Objc
module: VISPER-Objc
framework_root: Classes
podspec: "VISPER-Objc.podspec" 
