// Generated using Sourcery 0.10.1 — https://github.com/krzysztofzablocki/Sourcery
// DO NOT EDIT

// Generated by AutoReducer.stencil

// "sourcery-internal" - most likely not relevant to developers because reducers are auto created and used.

import VISPER_Redux
import VISPER_Core

//
// AppState


// Action for modifying property styleState found in AppState
internal struct AppStateSetStylestateAction: Action {
    let styleState: StyleState
    internal init(styleState: StyleState) {
        self.styleState = styleState
    }
}

// Set AppState styleState Action Reducer
internal class AppStateSetStylestateReducer: ActionReducerType {
    public typealias ReducerStateType = AppState
    public typealias ReducerActionType = AppStateSetStylestateAction
    public func reduce(provider: ReducerProvider,
                         action: AppStateSetStylestateAction,
                          state: AppState) -> AppState {
        if let newState = AppState(sourceObject: state, styleState: action.styleState) {
            return newState
        } else {
            return state
        }
    }
}



// Action for modifying property userState found in AppState
internal struct AppStateSetUserstateAction: Action {
    let userState: UserState?
    internal init(userState: UserState?) {
        self.userState = userState
    }
}

// Set AppState userState Action Reducer
internal class AppStateSetUserstateReducer: ActionReducerType {
    public typealias ReducerStateType = AppState
    public typealias ReducerActionType = AppStateSetUserstateAction
    public func reduce(provider: ReducerProvider,
                         action: AppStateSetUserstateAction,
                          state: AppState) -> AppState {
        if let newState = AppState(sourceObject: state, userState: action.userState) {
            return newState
        } else {
            return state
        }
    }
}

//
// StyleState


// Action for modifying property backgroundColor found in StyleState
internal struct StyleStateSetBackgroundcolorAction: Action {
    let backgroundColor: UIColor
    internal init(backgroundColor: UIColor) {
        self.backgroundColor = backgroundColor
    }
}

// Set StyleState backgroundColor Action Reducer
internal class StyleStateSetBackgroundcolorReducer: ActionReducerType {
    public typealias ReducerStateType = StyleState
    public typealias ReducerActionType = StyleStateSetBackgroundcolorAction
    public func reduce(provider: ReducerProvider,
                         action: StyleStateSetBackgroundcolorAction,
                          state: StyleState) -> StyleState {
        if let newState = StyleState(sourceObject: state, backgroundColor: action.backgroundColor) {
            return newState
        } else {
            return state
        }
    }
}



// Action for modifying property fontColor found in StyleState
internal struct StyleStateSetFontcolorAction: Action {
    let fontColor: UIColor
    internal init(fontColor: UIColor) {
        self.fontColor = fontColor
    }
}

// Set StyleState fontColor Action Reducer
internal class StyleStateSetFontcolorReducer: ActionReducerType {
    public typealias ReducerStateType = StyleState
    public typealias ReducerActionType = StyleStateSetFontcolorAction
    public func reduce(provider: ReducerProvider,
                         action: StyleStateSetFontcolorAction,
                          state: StyleState) -> StyleState {
        if let newState = StyleState(sourceObject: state, fontColor: action.fontColor) {
            return newState
        } else {
            return state
        }
    }
}

//
// UserState


// Action for modifying property firstName found in UserState
internal struct UserStateSetFirstnameAction: Action {
    let firstName: String?
    internal init(firstName: String?) {
        self.firstName = firstName
    }
}

// Set UserState firstName Action Reducer
internal class UserStateSetFirstnameReducer: ActionReducerType {
    public typealias ReducerStateType = UserState
    public typealias ReducerActionType = UserStateSetFirstnameAction
    public func reduce(provider: ReducerProvider,
                         action: UserStateSetFirstnameAction,
                          state: UserState) -> UserState {
        if let newState = UserState(sourceObject: state, firstName: action.firstName) {
            return newState
        } else {
            return state
        }
    }
}



// Action for modifying property lastName found in UserState
internal struct UserStateSetLastnameAction: Action {
    let lastName: String?
    internal init(lastName: String?) {
        self.lastName = lastName
    }
}

// Set UserState lastName Action Reducer
internal class UserStateSetLastnameReducer: ActionReducerType {
    public typealias ReducerStateType = UserState
    public typealias ReducerActionType = UserStateSetLastnameAction
    public func reduce(provider: ReducerProvider,
                         action: UserStateSetLastnameAction,
                          state: UserState) -> UserState {
        if let newState = UserState(sourceObject: state, lastName: action.lastName) {
            return newState
        } else {
            return state
        }
    }
}



// Action for modifying property userName found in UserState
internal struct UserStateSetUsernameAction: Action {
    let userName: String
    internal init(userName: String) {
        self.userName = userName
    }
}

// Set UserState userName Action Reducer
internal class UserStateSetUsernameReducer: ActionReducerType {
    public typealias ReducerStateType = UserState
    public typealias ReducerActionType = UserStateSetUsernameAction
    public func reduce(provider: ReducerProvider,
                         action: UserStateSetUsernameAction,
                          state: UserState) -> UserState {
        if let newState = UserState(sourceObject: state, userName: action.userName) {
            return newState
        } else {
            return state
        }
    }
}



// Action for modifying property email found in UserState
internal struct UserStateSetEmailAction: Action {
    let email: String?
    internal init(email: String?) {
        self.email = email
    }
}

// Set UserState email Action Reducer
internal class UserStateSetEmailReducer: ActionReducerType {
    public typealias ReducerStateType = UserState
    public typealias ReducerActionType = UserStateSetEmailAction
    public func reduce(provider: ReducerProvider,
                         action: UserStateSetEmailAction,
                          state: UserState) -> UserState {
        if let newState = UserState(sourceObject: state, email: action.email) {
            return newState
        } else {
            return state
        }
    }
}








