---
min_acl: public
github_url: https://github.com/barteljan/VISPER.git
readme: ../docs/README-VISPER-Swift.md
author: Jan Bartel
clean:
sdk: iphonesimulator
output: ../docs/VISPER-Swift
module: VISPER-Swift
framework_root: Classes
podspec: "VISPER-Swift.podspec" 
