---
min_acl: public
github_url: https://github.com/barteljan/VISPER.git
readme: ../docs/README-VISPER-Redux.md
author: Jan Bartel
clean:
sdk: iphonesimulator
output: ../docs/VISPER-Redux
module: VISPER-Redux
framework_root: Classes
podspec: "VISPER-Redux.podspec" 
