//
//  Bridge-Wireframe.swift
//  VISPER
//
//  Created by bartel on 06.01.18.
//

import Foundation
import VISPER_Wireframe

public typealias ModalControllerDismisser = VISPER_Wireframe.ModalControllerDismisser
public typealias NavigationControllerDismisser = VISPER_Wireframe.NavigationControllerDismisser

public typealias AnimatedRoutingOption = VISPER_Wireframe.AnimatedRoutingOption
public typealias RoutingOptionBackTo = VISPER_Wireframe.RoutingOptionBackTo
public typealias DefaultRoutingBackTo = VISPER_Wireframe.DefaultRoutingBackTo
public typealias RoutingOptionGetController = VISPER_Wireframe.RoutingOptionGetController
public typealias DefaultRoutingOptionGetController = VISPER_Wireframe.DefaultRoutingOptionGetController
public typealias RoutingOptionModal = VISPER_Wireframe.RoutingOptionModal
public typealias DefaultRoutingOptionModal = VISPER_Wireframe.DefaultRoutingOptionModal
public typealias RoutingOptionPush = VISPER_Wireframe.RoutingOptionPush
public typealias DefaultRoutingOptionPush = VISPER_Wireframe.DefaultRoutingOptionPush
public typealias RoutingOptionReplaceTopVC = VISPER_Wireframe.RoutingOptionReplaceTopVC
public typealias DefaultRoutingOptionReplaceTopVC = VISPER_Wireframe.DefaultRoutingOptionReplaceTopVC
public typealias RoutingOptionRootVC = VISPER_Wireframe.RoutingOptionRootVC
public typealias DefaultRoutingOptionRootVC = VISPER_Wireframe.DefaultRoutingOptionRootVC
public typealias RoutingOptionShow = VISPER_Wireframe.RoutingOptionShow
public typealias DefaultRoutingOptionShow = VISPER_Wireframe.DefaultRoutingOptionShow

public typealias BackToRoutingPresenterError = VISPER_Wireframe.BackToRoutingPresenterError
public typealias BackToRoutingPresenter = VISPER_Wireframe.BackToRoutingPresenter
public typealias ControllerContainerAwareRoutingPresenter = VISPER_Wireframe.ControllerContainerAwareRoutingPresenter
public typealias DefaultControllerContainerAwareRoutingPresenter = VISPER_Wireframe.DefaultControllerContainerAwareRoutingPresenter
public typealias ModalRoutingPresenterError = VISPER_Wireframe.ModalRoutingPresenterError
public typealias ModalRoutingPresenter = VISPER_Wireframe.ModalRoutingPresenter
public typealias PushRoutingPresenterError = VISPER_Wireframe.PushRoutingPresenterError
public typealias PushRoutingPresenter = VISPER_Wireframe.PushRoutingPresenter
public typealias ReplaceTopVCRoutingPresenterError = VISPER_Wireframe.ReplaceTopVCRoutingPresenterError
public typealias ReplaceTopVCRoutingPresenter = VISPER_Wireframe.ReplaceTopVCRoutingPresenter
public typealias RootVCRoutingPresenterError = VISPER_Wireframe.RootVCRoutingPresenterError
public typealias RootVCRoutingPresenter = VISPER_Wireframe.RootVCRoutingPresenter
public typealias ShowRoutingPresenterError = VISPER_Wireframe.ShowRoutingPresenterError
public typealias ShowRoutingPresenter = VISPER_Wireframe.ShowRoutingPresenter

public typealias ChildViewControllerTopControllerResolver = VISPER_Wireframe.ChildViewControllerTopControllerResolver
public typealias ModalViewControllerTopControllerResolver = VISPER_Wireframe.ModalViewControllerTopControllerResolver
public typealias NavigationControllerTopControllerResolver = VISPER_Wireframe.NavigationControllerTopControllerResolver
public typealias TabbarControllerTopControllerResolver = VISPER_Wireframe.TabbarControllerTopControllerResolver


public typealias ComposedControllerDimisser = VISPER_Wireframe.ComposedControllerDimisser
public typealias ComposedControllerProvider = VISPER_Wireframe.ComposedControllerProvider
public typealias ComposedPresenterProvider = VISPER_Wireframe.ComposedPresenterProvider
public typealias ComposedRoutingObserver = VISPER_Wireframe.ComposedRoutingObserver
public typealias ComposedRoutingOptionProvider = VISPER_Wireframe.ComposedRoutingOptionProvider
public typealias ComposedRoutingPresenter = VISPER_Wireframe.ComposedRoutingPresenter
public typealias ComposedTopControllerResolver = VISPER_Wireframe.ComposedTopControllerResolver
public typealias DefaultComposedControllerDismisser = VISPER_Wireframe.DefaultComposedControllerDismisser
public typealias DefaultComposedControllerProviderError = VISPER_Wireframe.DefaultComposedControllerProviderError
public typealias DefaultComposedControllerProvider = VISPER_Wireframe.DefaultComposedControllerProvider
public typealias DefaultComposedPresenterProvider = VISPER_Wireframe.DefaultComposedPresenterProvider
public typealias DefaultComposedRoutingObserver = VISPER_Wireframe.DefaultComposedRoutingObserver
public typealias DefaultComposedRoutingOptionProvider = VISPER_Wireframe.DefaultComposedRoutingOptionProvider
public typealias DefaultComposedRoutingPresenter = VISPER_Wireframe.DefaultComposedRoutingPresenter
public typealias DefaultComposedTopControllerResolver = VISPER_Wireframe.DefaultComposedTopControllerResolver
public typealias DefautRouterError = VISPER_Wireframe.DefautRouterError
public typealias DefaultRouter = VISPER_Wireframe.DefaultRouter
public typealias DefaultRouteResult = VISPER_Wireframe.DefaultRouteResult
public typealias DefaultRouteResultHandler = VISPER_Wireframe.DefaultRouteResultHandler
public typealias DefaultRoutingDelegate = VISPER_Wireframe.DefaultRoutingDelegate
public typealias DefaultRoutingHandlerContainer = VISPER_Wireframe.DefaultRoutingHandlerContainer
public typealias DefaultWireframeError = VISPER_Wireframe.DefaultWireframeError
public typealias DefaultWireframe = VISPER_Wireframe.DefaultWireframe
public typealias FunctionalControllerProvider = VISPER_Wireframe.FunctionalControllerProvider
public typealias FunctionalRoutingOptionProvider = VISPER_Wireframe.FunctionalRoutingOptionProvider
public typealias Router = VISPER_Wireframe.Router
public typealias RouteResultHandler = VISPER_Wireframe.RouteResultHandler
public typealias RoutingHandlerContainer = VISPER_Wireframe.RoutingHandlerContainer
public typealias WireframeFactory = VISPER_Wireframe.WireframeFactory

public typealias DefaultWireframeApp = VISPER_Wireframe.DefaultWireframeApp
public typealias PresenterFeature = VISPER_Wireframe.PresenterFeature
public typealias PresenterFeatureObserver = VISPER_Wireframe.PresenterFeatureObserver
public typealias ViewFeature = VISPER_Wireframe.ViewFeature
public typealias ViewFeatureObserver = VISPER_Wireframe.ViewFeatureObserver
public typealias WireframeApp = VISPER_Wireframe.WireframeApp
public typealias WireframeFeatureObserver = VISPER_Wireframe.WireframeFeatureObserver
public typealias WireframeAppFactory = VISPER_Wireframe.WireframeAppFactory
public typealias DefaultWireframeAppFactory = VISPER_Wireframe.DefaultWireframeAppFactory
