---
min_acl: public
github_url: https://github.com/barteljan/VISPER.git
readme: ../docs/README-VISPER-UIViewController.md
author: Jan Bartel
clean:
sdk: iphonesimulator
output: ../docs/VISPER-UIViewController/swift
module: VISPER-Core
framework_root: Classes/swift
podspec: "VISPER-UIViewController.podspec" 
