---
min_acl: public
github_url: https://github.com/barteljan/VISPER.git
readme: ../README.md
author: Jan Bartel
clean:
sdk: iphonesimulator
output: ../docs/VISPER
module: VISPER
framework_root: Classes
podspec: "VISPER.podspec" 
